[project]
name = "naturelm"
version = "0.1.0"
description = "naturelm"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=0.26.0",
    "bitsandbytes>=0.46.0",
    "datasets>=3.6.0",
    "sentencepiece>=0.2.0",
    "transformers>=4.52.4",
]
